name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Run Container

        run: docker compose -f /home/pi/Bot_Data/ifunny_crusader/docker-compose.yml up -d --build

      - name: Cleanup Unused Images
        run: sudo docker image prune -f